name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create .tar.gz archive
      run: |
        tar -czf language-installer.tar.gz install.sh README.md LICENSE

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: language-installer.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
